"""Kiswahili TIE rule strings shared by teacher-plan generation prompts."""

from __future__ import annotations

# Kiswahili translation of the shared TIE lesson-plan rules.
_TIE_LESSON_PLAN_RULES_SW = (
    "KANUNI ZISIZOBADILISHA (lazima zote zitimie):\n"
    "1. Ujuzi Mkuu na Ujuzi Mahususi ni TAARIFA halisi za ujuzi kutoka misingumo ya "
    "TIE, kwa maneno kwa maneno, zenye misimbo yao wenyewe (main_code / specific_code), "
    "k.m. \"3.0 Kuonyesha ustadi wa dhana na ujuzi wa msingi\" na \"3.1 Kutumia [...] "
    "katika maisha ya kila siku\". Ujuzi Mkuu ni taarifa pana ya matokeo (inaanza kama "
    "\"Kuonyesha ustadi wa\", \"Kutumia\", \"Kuendesha\"), na Ujuzi Mahususi ni taarifa "
    "nyembamba inayohusiana nayo. Haziwezi kamwe kuwa jina la mada au sehemu ya mada. "
    "Nakili kikamilifu kipengele cha REAL COMPETENCES kama kimetolewa. Jina la mada "
    "huwekwa tu kwenye header.topic na jina la sehemu ya mada kwenye header.subtopic; "
    "usiviweke kwenye sehemu za ujuzi kwa hali yoyote.\n"
    "2. Shughuli kuu ni maelezo mapana ya kujifunza kwa mada (kutoka misingumo); "
    "shughuli mahususi ni SHUGHULI MAHUSUSI MOJA ya kujifunza inayolenga somo hili, "
    "ikiandikwa kama kishazi fupi cha matokeo (mf. \"Fafanua sifa za vitendakazi "
    "hyperbolic\"). INAFAAANA SI kishazi chenye muda kama \"Ndani ya dakika N...\".\n"
    "3. Tumia haswa majina manne rasmi ya hatua kwa utaratibu: Utangulizi, Ukuzaji wa "
    "Ujuzi, Usanifu, na Utambuzi.\n"
    "4. Kigezo cha tathmini cha kila hatua lazima kiwe TATHMINI MAHUSUSI ya hatua "
    "hiyo: lazima kikague kwa uwazi kile MWALIMU anachofanya NA kile WANAFUNZI "
    "wanachofanya katika hatua hiyo, kikitaja kitendo + kitendo cha mwanafunzi + "
    "hali ya mafanikio (mf. \"Kutathmini shughuli ya mwalimu ya uongozi (anaongoza "
    "makundi kubadilisha muktadha kuwa milinganyo), angalia kama wanafunzi "
    "wanabadilisha muktadha kuwa milinganyo na kuitatua kwa usahihi.\"). Tumia "
    "sentensi tofauti kwa kila hatua - usirudie sentensi ya kawaida kama "
    "\"Wanafunzi wanaelewa dhana\" au \"Wanafunzi hutumia kwa usahihi shughuli\".\n"
    "5. Tumia tu mada/sehemu za mada/matokeo yaliyopo kwenye misingumo. Usibuni "
    "maudhui; kama mada au sehemu ya mada haipo, sema hivyo badala ya kubuni.\n"
    "6. Marejeo lazima yanukuu kitabu rasmi cha TIE (somo, mwaka, kidato); rasilimali na "
    "mazingira ya kujifunzia lazima vitoke kwenye misingumo.\n\n"
    "UFUATILIAJI WA UKAGUZI WA SQAD — UBORA WA 100% KWA UKAGUZI WA WIZARA YA ELIMU:\n"
    "7. UHALISI WA MTAALA: Ujuzi Mkuu, Ujuzi Mahususi, na Shughuli Kuu lazima ziwe "
    "KAMILI KWA MANENO kutoka misingumo ya TIE — maneno kwa maneno, si kwa maelezo. "
    "Shughuli Mahususi lazima iwe kichwa kidogo kilichogawanywa kutoka Shughuli Kuu.\n"
    "8. ODHOSHA YA WAFUATILIAJI: Jaza students_present kwa nambari halisi (wavulana, "
    "wasichana, jumla). Acha students_absent kama zilizoachwa (zilizosajiliwa "
    "kuzidisha zilizopo). Hii inaunda meza ya 3 kolamu ya SQAD (Zilizosajiliwa / "
    "Zilizopo / Zilizokosekana).\n"
    "9. LENGO LA SOMO: Andika lengo la SMART kwa muundo: \"Mwisho wa somo hili la "
    "dakika {duration_minutes}, mwanafunzi anapaswa kuwa na uwezo wa [KITENDO CHA "
    "SMART] [mada mahususi] kwa usahihi.\" Tumia vitendo vinavyoweza kupimika: "
    "tambua, fafanua, hesabu, jenga, eleza, onyesha, mgawanyiko, uchambuzi. Usitumie "
    "maneno ya kawaida kama \"elewa\" au \"jua\".\n"
    "10. MWALIMU WA KILA HATUA: Kila hatua ya mchakato wa hatua 4 lazima iwe na "
    "sehemu ya core_content inayoeleza ujuzi mkuu/ujuzi unaoshughulikiwa katika "
    "hatua hiyo (mf. \"Maarifa ya awali\", \"Dhana na vipengele vya msingi\", "
    "\"Matumizi ya vitendo\", \"Uonyeshaji na ukomavu\").\n"
    "11. VIFAA VYA KUTUMIA: Rasilimali lazima ziwe MAHALUSI — nachukua vitabu halisi "
    "vyenye jina la somo na kidato (mf. \"TIE Hisabati kwa Shule za Sekondari "
    "Kidato 2, uk. 45-48\"), vifaa halisi (vipimo, kompyuta, samani za maabara), "
    "na vifaa halisi (chanti, karatazi za kazi, vifaa vya maabara). Usiorodheshe "
    "sehemu za kujaza kama \"Bao na Ubao\" au \"asilimia mbalimbali\".\n"
    "12. MUUNDO WA MAREJEO: Lazima ufuate muundo wa kitaaluma: Mwandishi (Mwaka). "
    "Kichwa. Jiji: Mchapishaji, Ukurasa. Mfano: \"TIE (2023). Hisabati kwa Shule "
    "za Sekondari Kitabu cha Mwanafunzi Kidato 2, uk. 45-48. Dar es Salaam: TIE.\"\n\n"
    "UBORA WA MAUDHUI — Wewe ni MWANDISHI wa mtaalamu wa mtaala, SI NAKALA YA DATA:\n"
    "13. USINAKILI pointi ghafi za misingumo moja kwa moja kwenye shughuli. ZIBADILISHE "
    "kuwa sentensi kamili, za kitaalamu ambazo mwalimu halisi angeschandikwa. Kila "
    "maelezo ya shughuli lazima yawe sentensi yenye kiini chake, miliya sahihi, na "
    "mtindo wa kitaalamu.\n"
    "14. Shughuli za mwalimu lazima zieleze HATUA ZA WATENDAJI ambazo mwalimu anafanya: "
    "\"Anaongoza wanafunzi kupitia...\", \"Anaonyesha...\", \"Anarahisisha kazi ya "
    "vikundi kuhusu...\", \"Anawapa kazi ya kujifunza peke yao...\", \"Anakusanya na "
    "kukagua...\". Epuka maneno ya kawaida kama \"Anafundisha kuhusu...\" au \"Anashughulikia "
    "mada ya...\".\n"
    "15. Shughuli za mwanafunzi lazima zieleze HATUA ZA WATENDAJI ambazo mwanafunzi "
    "anafanya: \"Anatambua...\", \"Anajadiliana na rafiki yake...\", \"Anakamilisha...\", "
    "\"Anaandika...\", \"Anaonyesha matokeo...\". Epuka maneno ya kawaida kama \"Anajifunza "
    "kuhusu...\".\n"
    "16. Lugha na uandishi: kila sentensi lazima iwe sahihi kwa sarufi, yenye alama "
    "sahihi, na bila makosa ya herufi. Tumia Kiswahili rasmi, cha kitaalamu. Epuka "
    "vipindi (si → si, havija → havija). Tumia maneno sawia kote.\n"
    "17. SEHEMU YA TATHMINI: Jumuishisha sehemu ya evaluation yenye sehemu mbili "
    "zilizoachwa kwa uandishi wa mkono baada ya somo:\n"
    "    - evaluation_learners: \"[Itakamilishwa baada ya somo: mf., Wanafunzi 38 "
    "kati ya 45 walifanikiwa kuunda dhana. Wanafunzi 7 walipata matatizo.]\"\n"
    "    - evaluation_teacher: \"[Itakamilishwa baada ya somo: mf., Kazi ya vikundi "
    "katika Ukuzaji wa Ujuzi ilikuwa nzuri. Hatua ya Usanifu ilihitaji dakika 5 "
    "za ziada.]\"\n"
    "18. Kabla ya kutoa JSON, fanya ukaguzi wa kimyakimya dhidi ya ukaguzi huu:\n"
    "    a. Je, ujuzi wote 4 upo, haujaa, na ni kamili kwa maneno kutoka misingumo?\n"
    "    b. Je, shughuli mahususi ina matokeo halisi, fupi (si ya kawaida)?\n"
    "    c. Je, lenjo la somo ni sentensi yenye kitendo kinachoweza kupimika?\n"
    "    d. Je, vigezo vya tathmini vya hatua zote 4 vinaerejea shughuli mahususi "
    "kwa usahihi?\n"
    "    e. Je, kila hatua ina sehemu ya core_content?\n"
    "    f. Je, shughuli za mwalimu na mwanafunzi ni za vitendo na tofauti kwa "
    "mwendo?\n"
    "    g. Je, rasilimali ni mahalusi na zina ukurasa wa kitabu (si sehemu za kujaza)?\n"
    "    h. Je, marejeo ni kwa muundo wa kitaaluma (Mwandishi, Mwaka, Kichwa, "
    "Jiji, Ukurasa)?\n"
    "     i. Je, evaluation_learners na evaluation_teacher zipo kama sehemu za kujaza?\n"
    "    j. Je, kila sentensi ni sahihi kwa sarufi na imeandikwa kitaalamu?\n"
    "    k. Je, kigezo cha tathmini cha kila hatua kinatathmini mahususi shughuli za "
    "mwalimu na mwanafunzi za hatua hiyo (si maneno ya kawaida)?\n"
    "   Kama ukaguzi yoyote unashindwa, SAHISHA tatizo kabla ya kutoa. USITOE "
    "maudhui yasiyo kamili au ya ubora wa chini.\n"
)


_TIE_SCHEME_RULES_SW = (
    "\nKANUNI ZISIZOBADILISHA (lazima zote zitimie):\n"
    "1. UADILIFU WA VIPINDI: jumla ya vipindi vya mada LAZIMA ilingane na jumla "
    "ya vipindi vya sehemu zake za mada; jumla ya somo kwa kidato LAZIMA ilingane "
    "na jumla ya vipindi vya sehemu zote za mada. Usiongeze au upunguze vipindi "
    "alivyotenga misingumo — mpango huamua tu JINSI kila kipindi kinavyotumika.\n"
    "2. UJUZI hubeba misimbo ya misingumo: mkuu = '{topic code} {topic title}', "
    "mahususi = '{subtopic code} {subtopic title}'.\n"
    "3. SHUGHULI ZA KUJIFUNZA: orodhesha shughuli halisi (matokeo) kutoka misingumo "
    "kwa kila sehemu ya mada; gauza vipindi vilivyotengwa vya sehemu ya mada kati "
    "yake ili kila shughuli ipate uzito wake wa vipindi.\n"
    "4. KALENDA: muhula 2 — Muhula wa Kwanza = Jan–Mei, wa Pili = Jul–Nov, wiki 4 "
    "kwa mwezi. Ingiza haswa wiki MBILI zisizofundisha katikati ya muhula na "
    "vipindi=0: 'MTIHANI WA MUHULA' na 'LIKIZO LA MUHULA'. Nambari za wiki "
    "zisalie mfululizo.\n"
    "5. UHALISI: tumia tu mada/sehemu za mada/matokeo yaliyopo kwenye misingumo. "
    "Usibuni mada wala hesabu za vipindi. Marejeo yanukuu kitabu rasmi cha TIE "
    "(somo, mwaka, kidato).\n"
    "6. Toa JSON SAHIHI inayolingana na muundo; bila maelezo ya ziada.\n\n"
    "UFUATILIAJI WA UKAGUZI WA SQAD — UBORA WA 100% KWA UKAGUZI WA WIZARA YA ELIMU:\n"
    "7. MUUNDO WA KOLAMU 12: Mpango lazima uwe na kolamu 12 kwa utaratibu huu: "
    "Mwezi, Wiki, Ujuzi Mkuu, Ujuzi Mahususi, Shughuli Kuu ya Kujifunza, Shughuli "
    "Mahususi ya Kujifunza, Idadi ya Vipindi, Shughuli za Kufundisha na Kujifunza, "
    "Vigezo vya Tathmini, Rasilimali za Kufundisha na Kujifunza, Marejeo, Maelezo.\n"
    "8. UHALISI WA MTAALA: Ujuzi Mkuu, Ujuzi Mahususi, na Shughuli Kuu ya Kujifunza "
    "lazima ziwe KAMILI KWA MANENO kutoka misingumo ya TIE — maneno kwa maneno, si "
    "kwa maelezo. Shughuli Mahususi lazima iwe kichwa kidogo kilichogawanywa kutoka "
    "Shughuli Kuu.\n"
    "9. UBORA WA KOGNITIVI: Lengo la kujifunza lazima lianze na kazi rahisi katika "
    "wiki za kwanza na liendelee hadi ujuzi changamano katika wiki za baadaye ndani "
    "ya mada. Wiki ya 1 ya mada lazima ifunike maarifa ya msingi; wiki za baadaye "
    "zijenge hadi matumizi na uchambuzi.\n"
    "10. SHUGHULI ZA KUFUNDISHA NA KUJIFUNZA: Kolamu hii lazima iwe na HATUA ZA "
    "TOFAUTI kwa Mwalimu na Mwanafunzi — si pamoja. Muundo: \"Mwalimu: [hatua]. "
    "Mwanafunzi: [hatua].\" Usiwaunganishe kwa sentensi moja.\n"
    "11. MUUNDO WA MAREJEO: Lazima ufuate muundo wa kitaaluma: Mwandishi (Mwaka). "
    "Kichwa. Jiji: Mchapishaji, Ukurasa. Mfano: \"TIE (2023). Hisabati kwa Shule "
    "za Sekondari Kitabu cha Mwanafunzi Kidato 2, uk. 45-48. Dar es Salaam: TIE.\"\n"
    "12. MAELEZO: Acha sehemu hii kuwa tupu. Lazima iandikwe kwa mkono baada ya "
    "kufundisha na takwima halisi (mf., 'Kati ya wanafunzi 45, 40 walifanikiwa. "
    "Wanafunzi 5 watapata msaada wa ziada tarehe 14/02/2026.').\n\n"
    "UBORA WA MAUDHUI — Wewe ni MTAALAMU wa kupanga mtaala, SI NAKALA YA DATA:\n"
    "13. USINAKILI pointi ghafi za misingumo moja kwa moja kwenye shughuli za "
    "kujifunza. ZIBADILISHE kuwa taarifa wazi, za kitaalamu ambazo mwalimu halisi "
    "angetambua. Kila shughuli lazima iwe kifaa kamili chenye istilahi sahihi.\n"
    "14. Mbinu za kufundisha lazima ziwe MAHALUSI NA ZA PEDAGOJIA: orodhesha mbinu "
    "halisi (Mjadala wa kikundi, Utatuzi wa matatizo, Uonyeshaji, Kazi ya vitanda, "
    "Kazi ya maabara, Kujifunza kwa mradi). Epuka sehemu za kujaza kama "
    "\"mbalimbali\" au \"mchanganyiko wa mbinu\".\n"
    "15. Rasilimali lazima ziwe MAHALUSI NA ZINAZOFAA: orodhesha vitabu halisi "
    "(jina + kidato + ukurasa), vifaa halisi (vipimo, kompyuta, samani za maabara), "
    "na vifaa halisi (chanti, karatazi za kazi, vifaa vya maabara). Usiorodheshe "
    "\"asilimia mbalimbali\".\n"
    "16. Zana za tathmini lazima ziwe ZA KIVITENDO: 'Maswali ya mtihani, maswali "
    "ya mdomo, mitihani ya maandishi, maonyesho ya vikundi, uthibitisho wa "
    "vifaa'. Epuka sehemu za kujaza kama \"zana mbalimbali\".\n"
    "17. Lugha na uandishi: kila sentensi lazima iwe sahihi kwa sarufi, yenye "
    "alama sahihi, na bila makosa ya herufi. Tumia Kiswahili rasmi, cha "
    "kitaalamu. Epuka vipindi (si → si, havija → havija). Tumia maneno "
    "sawia kote.\n"
    "18. Kabla ya kutoa JSON, fanya ukaguzi wa kimyakimya dhidi ya ukaguzi huu:\n"
    "    a. Je, jumla ya vipindi ya mada na sehemu za mada zinaongea?\n"
    "    b. Je, ujuzi wote una misimbo, haunjaa, na ni kamili kwa maneno kutoka TIE?\n"
    "    c. Je, shughuli za kujifunza ni matokeo halisi (si ya kubuni)?\n"
    "    d. Je, Shughuli Kuu katika kila safu ni kamili kutoka TIE na Shughuli "
    "Mahususi ni kichwa kidogo kilichogawanywa?\n"
    "    e. Je, Shughuli za Kufundisha na Kujifunza zimegawanywa kwa hatua za "
    "Tofauti za Mwalimu na Mwanafunzi?\n"
    "    f. Je, mbinu ni mahalusi (si sehemu za kujaza)?\n"
    "    g. Je, rasilimali ni mahalusi na zina ukurasa wa kitabu (si sehemu za kujaza)?\n"
    "    h. Je, marejeo ni kwa muundo wa kitaaluma (Mwandishi, Mwaka, Kichwa, "
    "Jiji, Ukurasa)?\n"
    "    i. Je, sehemu ya Maelezo ni tupu (kwa uandishi wa mkono baada ya kufundisha)?\n"
    "    j. Je, ugumu wa kognitivi unakua kwa wiki ndani ya kila mada?\n"
    "    k. Je, kila sehemu ni sahihi kwa sarufi na imeandikwa kitaalamu?\n"
    "   Kama ukaguzi yoyote unashindwa, SAHISHA tatizo kabla ya kutoa. USITOE "
    "maudhui yasiyo kamili au ya ubora wa chini.\n"
)