"""English TIE rule strings shared by teacher-plan generation prompts."""

from __future__ import annotations

# Shared, authoritative rules for producing lesson plans that match the official
# TIE (Tanzania Institute of Education) competence-based format.
_TIE_LESSON_PLAN_RULES_EN = (
    "HARD RULES (must all hold):\n"
    "1. main_competence and specific_competence are the REAL, verbatim TIE syllabus "
    "competence STATEMENTS, carrying their own syllabus codes (main_code / "
    "specific_code), e.g. \"3.0 Demonstrate mastery of basic concepts and skills\" "
    "and \"3.1 Use [...] skills in daily life\". The Main Competence is a broad "
    "outcome statement (starts like \"Demonstrate mastery of\", \"Apply\", \"Use\", "
    "\"Conduct\"), and the Specific Competence is a narrower related statement. They "
    "are NEVER the topic title or subtopic title. Copy the REAL COMPETENCES block "
    "verbatim when one is supplied. The topic TITLE goes only in header.topic and "
    "the subtopic TITLE only in header.subtopic; do not put them in competence "
    "fields under any circumstances.\n"
    "2. main_learning_activity is the topic's broad learning narrative (from the syllabus "
    "context); specific_learning_activity is the SINGLE specific learning activity/outcome "
    "focused on this lesson, written as a concise outcome phrase (e.g. \"Define hyperbolic "
    "functions and their properties\"). It must NOT be a time-boxed sentence such as "
    "\"Within N minutes...\".\n"
    "3. Use exactly the four official stage names, in order: Introduction, Competence "
    "Development, Design, Realizations (always plural \"Realizations\").\n"
    "4. Each stage's assessment_criteria must be a UNIQUE, observable evaluation "
    "of THAT stage: it explicitly checks what the TEACHER does AND what the "
    "LEARNERS do in that stage, naming actor + action + success condition "
    "(e.g. \"Assessing the teacher's guided activity (guides groups to convert "
    "scenarios into equations), check whether learners correctly convert "
    "scenarios into equations and solve them.\"). Use a distinct sentence per "
    "stage - never reuse a generic line such as \"Students demonstrate "
    "understanding of the concept\" or \"Students correctly apply the activity\".\n"
    "5. Only use topics/subtopics/outcomes present in the curriculum context. Never invent "
    "content; if the requested topic/subtopic is absent, say so instead of fabricating.\n"
    "6. References must cite the real TIE book (subject, year, form); resources and learning "
    "environment must come from the syllabus context.\n\n"
    "SQAD AUDIT COMPLIANCE — 100% QUALITY FOR MINISTRY OF EDUCATION INSPECTION:\n"
    "7. CURRICULUM AUTHENTICITY: Main Competence, Specific Competence, and Main Learning "
    "Activity must be VERBATIM from the TIE syllabus — word-for-word, not paraphrased. "
    "The Specific Learning Activity must be a deconstructed micro-chunk of the Main Activity.\n"
    "8. STUDENT ATTENDANCE MATRIX: Fill students_present with actual numbers (boys, girls, "
    "total). Leave students_absent as the remainder (registered minus present). This creates "
    "the 3-column SQAD attendance table (Registered / Present / Absent).\n"
    "9. LESSON OBJECTIVE: Write a SMART objective sentence that starts with \"By the end "
    "of this {duration_minutes}-minute lesson, the learner should be able to\" followed by a "
    "measurable action verb (identify, define, calculate, construct, explain, demonstrate, "
    "classify, analyze) and the lesson's specific subject matter from the curriculum context, "
    "ending with \"accurately\". For example: \"By the end of this 40-minute lesson, the "
    "learner should be able to identify and apply the laws of indices accurately.\" "
    "Fill in the real, specific content — never leave bracketed placeholders in the final "
    "objective. Never use vague verbs like 'understand' or 'know'.\n"
    "10. CORE CONTENT per stage: Each of the 4 progression stages must include a "
    "core_content field stating the key knowledge/skill addressed in that stage "
    "(e.g. \"Prior knowledge foundation\", \"Core definitions and formulas\", "
    "\"Practical application\", \"Presentation and consolidation\").\n"
    "11. OPERATIONAL SOURCING: Resources must be SPECIFIC — cite exact textbook titles "
    "with form level (e.g. \"TIE Mathematics for Secondary Schools Form 2, pp. 45-48\"), "
    "actual tools (rulers, calculators, specimens), actual materials (charts, worksheets, "
    "lab equipment). Never list generic placeholders like \"Chalk and Blackboard\" or "
    "\"various resources\".\n"
    "12. REFERENCES FORMAT: Must follow academic citation: Author (Year). Title. City: "
    "Publisher, Pages. Example: \"TIE (2023). Mathematics for Secondary Schools "
    "Student's Book Form 2, pp. 45-48. Dar es Salaam: TIE.\"\n\n"
    "CONTENT QUALITY — YOU ARE AN EXPERT CURRICULUM WRITER, NOT A DATA COPIER:\n"
    "13. NEVER copy-paste raw syllabus bullet points into activities. TRANSFORM them "
    "into complete, professional sentences that a real teacher would write. Each activity "
    "description must be a full, grammatically correct sentence with proper subject-verb "
    "agreement, punctuation, and professional tone.\n"
    "14. Teacher activities must describe CONCRETE ACTIONS the teacher performs: "
    "\"Guides students through...\", \"Demonstrates...\", \"Facilitates group work on...\", "
    "\"Assigns individual practice...\", \"Collects and reviews...\". Avoid vague phrases "
    "like \"Teaches about...\" or \"Covers the topic of...\".\n"
    "15. Learner activities must describe CONCRETE ACTIONS the student performs: "
    "\"Identifies...\", \"Discusses in pairs...\", \"Completes...\", \"Writes...\", "
    "\"Presents findings...\". Avoid passive or vague phrases like \"Learns about...\".\n"
    "16. Grammar and spelling: every sentence must be grammatically correct, properly "
    "punctuated, and free of spelling errors. Use formal academic English. Avoid "
    "contractions (don't → do not, can't → cannot). Use consistent terminology "
    "throughout (don't switch between 'students', 'learners', 'pupils' randomly).\n"
    "17. EVALUATION SECTION: Include an evaluation field with two parts left as "
    "placeholders for handwritten completion after teaching:\n"
    "    - evaluation_learners: \"[To be completed after lesson: e.g., 38 out of 45 "
    "students successfully modeled the concept. 7 students struggled with application "
    "due to computation errors.]\"\n"
    "    - evaluation_teacher: \"[To be completed after lesson: e.g., Group work in "
    "Competence Development was effective. Design phase required extra 5 minutes. "
    "Future sessions will feature tighter task transitions.]\"\n"
    "18. Before outputting the JSON, silently evaluate your work against these checks:\n"
    "    a. Are all 4 competences present, non-empty, and verbatim from syllabus?\n"
    "    b. Does specific_learning_activity contain a real, concise outcome (not generic)?\n"
    "    c. Is lesson_objective a SMART sentence with a measurable verb?\n"
    "    d. Do all 4 assessment criteria echo the specific activity correctly?\n"
    "    e. Does each stage have a core_content field?\n"
    "    f. Are teacher and learner activities concrete and different from each other?\n"
    "    g. Are resources specific with textbook pages (not placeholders)?\n"
    "    h. Are references in academic citation format (Author, Year, Title, City, Pages)?\n"
    "     i. Is evaluation_learners and evaluation_teacher present as placeholders?\n"
    "    j. Is every sentence grammatically correct and professionally written?\n"
    "    k. Does each stage's assessment_criteria uniquely evaluate that stage's "
    "teacher and learner activities (never generic filler)?\n"
    "   If any check fails, FIX the issue before outputting. Do NOT output incomplete "
    "or low-quality content.\n"
)


# Shared TIE rules for producing an authentic scheme of work.
_TIE_SCHEME_RULES_EN = (
    "\nHARD RULES (must all hold):\n"
    "1. PERIOD INTEGRITY: a topic's total periods MUST equal the sum of its "
    "subtopics' periods; the subject's total for the class MUST equal the sum of "
    "all subtopics' periods. Never add to or reduce the periods the syllabus "
    "allocates — the scheme only decides HOW each allocated period is used.\n"
    "2. COMPETENCES carry syllabus codes: main = '{topic code} {topic title}', "
    "specific = '{subtopic code} {subtopic title}'.\n"
    "3. LEARNING ACTIVITIES: list the exact learning activities (outcomes) from the "
    "curriculum context for each subtopic; distribute that subtopic's allocated "
    "periods across them so each activity gets its period weight.\n"
    "4. CALENDAR: 2 terms — Term I = Jan–May, Term II = Jul–Nov, 4 weeks/month. "
    "Insert exactly TWO non-teaching weeks at each term's midpoint with periods=0: "
    "'MIDTERM EXAMINATION' and 'MIDTERM HOLIDAY'. Week numbers stay continuous.\n"
    "5. AUTHENTICITY: use only topics/subtopics/outcomes present in the curriculum "
    "context. Never invent topics or period counts. References cite the real TIE "
    "book (subject, year, form).\n"
    "6. Output valid JSON matching the schema; no extra prose.\n\n"
    "SQAD AUDIT COMPLIANCE — 100% QUALITY FOR MINISTRY OF EDUCATION INSPECTION:\n"
    "7. 12-COLUMN FORMAT: The scheme must contain exactly 12 columns in this order: "
    "Month, Week, Main Competence, Specific Competence, Main Learning Activity, "
    "Specific Learning Activity, Number of Periods, Teaching & Learning Activities, "
    "Assessment Criteria, Teaching & Learning Resources, References, Remarks.\n"
    "8. CURRICULUM AUTHENTICITY: Main Competence, Specific Competence, and Main "
    "Learning Activity must be VERBATIM from the TIE syllabus — word-for-word, not "
    "paraphrased. The Specific Learning Activity must be a deconstructed micro-chunk "
    "of the Main Activity.\n"
    "9. COGNITIVE HIERARCHY: Learning objectives must progress from simple tasks in "
    "early weeks to complex competencies in later weeks within a topic. Week 1 of a "
    "topic should cover foundational knowledge; later weeks build toward application "
    "and analysis.\n"
    "10. TEACHING & LEARNING ACTIVITIES: This column must contain SEPARATE actions "
    "for Teacher and Learner — not combined. Format: \"Teacher: [action]. Learner: "
    "[action].\" Never merge them into a single statement.\n"
    "11. REFERENCES FORMAT: Must follow academic citation: Author (Year). Title. "
    "City: Publisher, Pages. Example: \"TIE (2023). Mathematics for Secondary "
    "Schools Student's Book Form 2, pp. 45-48. Dar es Salaam: TIE.\"\n"
    "12. REMARKS: Leave this field as an empty string. It must be handwritten after "
    "teaching with factual statistics (e.g., 'Out of 45 students, 40 performed "
    "successfully. 5 students will receive remedial instruction on 14/02/2026.').\n\n"
    "CONTENT QUALITY — YOU ARE AN EXPERT CURRICULUM PLANNER, NOT A DATA COPIER:\n"
    "13. NEVER copy-paste raw syllabus bullets into learning_activities. TRANSFORM "
    "them into clear, professional outcome statements that a real teacher would "
    "recognise. Each activity must be a complete phrase with proper terminology.\n"
    "14. Teaching methods must be SPECIFIC and PEDAGOGICALLY SOUND: list actual "
    "methods (Group discussion, Problem solving, Demonstration, Think-pair-share, "
    "Laboratory work, Project-based learning). Never list generic placeholders "
    "like 'various methods' or 'mixed approaches'.\n"
    "15. Teaching resources must be SPECIFIC and RELEVANT: list actual textbooks "
    "(title + form + pages), actual tools (rulers, calculators, specimens), actual "
    "materials (charts, worksheets, lab equipment). Never list 'various resources'.\n"
    "16. Assessment tools must be CONCRETE: 'Quizzes, oral questions, written tests, "
    "group presentations, practical demonstrations'. Never list 'various assessments'.\n"
    "17. Grammar and spelling: every sentence must be grammatically correct, properly "
    "punctuated, and free of spelling errors. Use formal academic English. Avoid "
    "contractions (don't → do not, can't → cannot). Use consistent terminology.\n"
    "18. Before outputting the JSON, silently evaluate your work against these checks:\n"
    "    a. Do all topic/subtopic period totals add up correctly?\n"
    "    b. Are all competences present with codes, non-empty, and verbatim from TIE?\n"
    "    c. Are learning activities real outcomes (not fabricated)?\n"
    "    d. Is each row's Main Activity verbatim from TIE and Specific Activity a "
    "deconstructed micro-chunk?\n"
    "    e. Are Teaching & Learning Activities split into separate Teacher/Learner actions?\n"
    "    f. Are teaching methods specific (not generic placeholders)?\n"
    "    g. Are resources specific with textbook pages (not placeholders)?\n"
    "    h. Are references in academic citation format (Author, Year, Title, City, Pages)?\n"
    "    i. Is Remarks field empty (for handwritten entry after teaching)?\n"
    "    j. Does cognitive complexity increase across weeks within each topic?\n"
    "    k. Is every field grammatically correct and professionally written?\n"
    "   If any check fails, FIX the issue before outputting. Do NOT output incomplete "
    "or low-quality content.\n"
)