"""Static development-seed data: subjects, form levels, topics, subtopics."""

subjects_data = [
    ("Mathematics", "mathematics"),
    ("Chemistry", "chemistry"),
    ("Physics", "physics"),
    ("Biology", "biology"),
    ("English", "english"),
    ("Kiswahili", "kiswahili"),
]

form_levels = ["I", "II", "III", "IV"]

topics_data = [
    ("mathematics", "Concept of Mathematics", "I"),
    ("mathematics", "Numbers", "I"),
    ("mathematics", "Approximations", "I"),
    ("mathematics", "Ratios and Proportions", "I"),
    ("mathematics", "Algebra", "I"),
    ("mathematics", "Coordinate Geometry", "I"),
    ("mathematics", "Geometry", "II"),
    ("mathematics", "Trigonometry", "III"),
    ("chemistry", "Introduction to Chemistry", "I"),
    ("chemistry", "Laboratory Techniques and Safety", "I"),
    ("chemistry", "Fire, Firefighting and Flames", "I"),
    ("chemistry", "Matter", "I"),
    ("chemistry", "Elements, Compounds and Mixtures", "I"),
    ("chemistry", "Chemical Bonding", "II"),
    ("physics", "Introduction to Physics", "I"),
    ("physics", "Measurement", "I"),
    ("physics", "Introduction to Force", "I"),
    ("physics", "Density and Relative Density", "I"),
    ("physics", "Sinking and Floating", "I"),
    ("physics", "Mechanical Properties of Matter", "I"),
    ("physics", "Pressure", "I"),
    ("physics", "Linear Motion", "I"),
    ("physics", "Work, Energy, and Power", "I"),
    ("physics", "Thermodynamics", "II"),
    ("biology", "Introduction to Biology", "I"),
    ("biology", "Scientific Processes in Biology", "I"),
    ("biology", "Cell Structure and Organization", "I"),
    ("biology", "Classification of Living Things", "I"),
    ("biology", "Viruses and Major Groups of Living Things", "I"),
    ("biology", "Nutrition in Plants", "I"),
    ("biology", "Genetics", "III"),
    ("english", "Using ICT Tools to Search for Information", "I"),
    ("english", "Listening to Various Types of Information", "I"),
    ("english", "Producing Short and Coherent Oral Messages", "I"),
    ("english", "Developing Vocabulary from Conversations and Written Texts", "I"),
    ("english", "Using Appropriate Grammar and Vocabulary in Oral and Written Contexts", "I"),
    ("english", "Reading Texts for Comprehension", "I"),
    ("english", "Comprehending Oral Messages", "I"),
    ("english", "Responding Through Oral and Written Communication", "I"),
    ("english", "Using Appropriate Grammar and Vocabulary for Oral Communication", "I"),
    ("english", "Creating a Variety of Texts Using Appropriate Tone and Register", "I"),
    ("english", "Literature", "II"),
    ("kiswahili", "Lugha na Utamaduni", "I"),
    ("kiswahili", "Sarufi ya Kiswahili", "I"),
    ("kiswahili", "Matumizi ya Kamusi", "I"),
    ("kiswahili", "Kusikiliza Mazungumzo", "I"),
    ("kiswahili", "Kusoma kwa Ufasahana na Ufahamu", "I"),
    ("kiswahili", "Kuwasiliana kwa njia ya Mazungumzo", "I"),
    ("kiswahili", "Kuwasiliana kwa njia ya Maandishi", "I"),
    ("kiswahili", "Fasihi", "II"),
]

subtopics_data = [
    ("Algebra", "Linear Equations"),
    ("Algebra", "Quadratic Equations"),
    ("Geometry", "Triangles"),
    ("Introduction to Chemistry", "Concept of Chemistry"),
    ("Introduction to Chemistry", "Relationships of Chemistry with other related disciplines"),
    ("Introduction to Chemistry", "Applications of Chemistry in the development of a modern society"),
    ("Laboratory Techniques and Safety", "Laboratory Safety Measures"),
    ("Laboratory Techniques and Safety", "Handling Chemicals Safely / Safety Signs"),
    ("Laboratory Techniques and Safety", "Laboratory Rules"),
    ("Laboratory Techniques and Safety", "First Aid and First Aid Kit"),
    ("Laboratory Techniques and Safety", "Basic Chemistry Laboratory Apparatus"),
    ("Fire, Firefighting and Flames", "Fire (Components needed to start fire)"),
    ("Fire, Firefighting and Flames", "Firefighting (Portable fire extinguishers)"),
    ("Fire, Firefighting and Flames", "Flames (Bunsen burner, parts, and characteristics of flames)"),
    ("Matter", "States of Matter"),
    ("Matter", "Changes in States of Matter"),
    ("Matter", "Particulate and Kinetic Nature of Matter"),
    ("Matter", "Physical and Chemical Changes"),
    ("Elements, Compounds and Mixtures", "Elements and Chemical Symbols"),
    ("Elements, Compounds and Mixtures", "Metals and Non-metals"),
    ("Elements, Compounds and Mixtures", "Compounds and Mixtures"),
    ("Elements, Compounds and Mixtures", "Solutions, Suspensions and Emulsions"),
    ("Elements, Compounds and Mixtures", "Separation of Mixtures"),
    ("Introduction to Physics", "Concept of Physics"),
    ("Introduction to Physics", "Contribution of Physics to the development of modern society"),
    ("Introduction to Physics", "Theories and principles of Physics"),
    ("Measurement", "Concept of Measurement"),
    ("Measurement", "Physical Quantity"),
    ("Measurement", "Basic Equipment/Apparatus and their uses"),
    ("Introduction to Force", "Concept of Force"),
    ("Introduction to Force", "Effects of Forces"),
    ("Introduction to Force", "Types of Forces"),
    ("Density and Relative Density", "Concept of Density"),
    ("Density and Relative Density", "Relative Density of a Substance"),
    ("Sinking and Floating", "Concept of Sinking and Floating"),
    ("Sinking and Floating", "Concept of Upthrust"),
    ("Sinking and Floating", "Archimedes' Principle"),
    ("Sinking and Floating", "Law of Floatation"),
    ("Mechanical Properties of Matter", "Concept of Elasticity"),
    ("Mechanical Properties of Matter", "Adhesion and Cohesion"),
    ("Mechanical Properties of Matter", "Surface Tension"),
    ("Mechanical Properties of Matter", "Capillarity"),
    ("Pressure", "Concept of Pressure"),
    ("Pressure", "Pressure due to Solids"),
    ("Pressure", "Pressure in Liquids"),
    ("Pressure", "Atmospheric Pressure"),
    ("Linear Motion", "Concept of Motion"),
    ("Linear Motion", "Distance and Displacement"),
    ("Linear Motion", "Speed and Velocity"),
    ("Linear Motion", "Acceleration"),
    ("Linear Motion", "Equation of Linear Motion"),
    ("Linear Motion", "Motion under Gravity"),
    ("Work, Energy, and Power", "Concept of Work"),
    ("Work, Energy, and Power", "Concept of Energy"),
    ("Work, Energy, and Power", "Concept of Power"),
    ("Introduction to Biology", "Basic Concepts and Terminologies in Biology"),
    ("Introduction to Biology", "Importance of Studying Biology"),
    ("Introduction to Biology", "Relationship between Biology and other Scientific Fields"),
    ("Scientific Processes in Biology", "Common Biology Laboratory Apparati, Equipment and Other Resources"),
    ("Scientific Processes in Biology", "Basic Skills in Scientific Studies"),
    ("Scientific Processes in Biology", "Scientific Methods"),
    ("Scientific Processes in Biology", "Simple Biological Experiments"),
    ("Cell Structure and Organization", "The Cell"),
    ("Cell Structure and Organization", "Types of Cells"),
    ("Cell Structure and Organization", "Cell Differentiation"),
    ("Classification of Living Things", "Concept of Classification"),
    ("Classification of Living Things", "Classification Systems"),
    ("Classification of Living Things", "Major Groups of Living Things"),
    ("Classification of Living Things", "Binomial Nomenclature"),
    ("Viruses and Major Groups of Living Things", "Viruses"),
    ("Viruses and Major Groups of Living Things", "Kingdom Monera"),
    ("Viruses and Major Groups of Living Things", "Kingdom Protoctista"),
    ("Viruses and Major Groups of Living Things", "Kingdom Fungi"),
    ("Viruses and Major Groups of Living Things", "Kingdom Plantae"),
    ("Viruses and Major Groups of Living Things", "Classes of the Division Angiospermophyta"),
    ("Viruses and Major Groups of Living Things", "Kingdom Animalia"),
    ("Nutrition in Plants", "Concept of Nutrition"),
    ("Nutrition in Plants", "Photosynthesis"),
    ("Nutrition in Plants", "Structure of the Leaf in Relation to Photosynthesis"),
    ("Nutrition in Plants", "Importance of Photosynthesis"),
    ("Nutrition in Plants", "Essential and Non-essential Elements in Plants"),
    ("Concept of Mathematics", "Meaning of Mathematics"),
    ("Concept of Mathematics", "Branches of Mathematics"),
    ("Concept of Mathematics", "Relationship between Mathematics and other Subjects"),
    ("Concept of Mathematics", "Importance of Mathematics"),
    ("Numbers", "Concept of Numbers"),
    ("Numbers", "Rational Numbers"),
    ("Numbers", "Irrational Numbers"),
    ("Numbers", "Real Numbers"),
    ("Numbers", "Inequalities in Real Numbers"),
    ("Numbers", "Absolute Value of a Real Number"),
    ("Approximations", "Meaning of Approximations"),
    ("Approximations", "Rounding off Numbers"),
    ("Approximations", "Significant Figures"),
    ("Approximations", "Approximations in Calculations"),
    ("Ratios and Proportions", "Ratios"),
    ("Ratios and Proportions", "Proportions"),
    ("Coordinate Geometry", "Basic Concepts of Coordinate Geometry"),
    ("Coordinate Geometry", "Gradient of a Straight Line"),
    ("Coordinate Geometry", "Equation of a Straight Line"),
    ("Coordinate Geometry", "General Equation of a Straight Line"),
    ("Coordinate Geometry", "Graphing Linear Equations"),
    ("Coordinate Geometry", "Solving Linear Simultaneous Equations Graphically"),
    ("Using ICT Tools to Search for Information", "Familiarising with various types of search engines and browsers"),
    ("Using ICT Tools to Search for Information", "Utilising ICT tools to search for general information"),
    ("Listening to Various Types of Information", "Answering questions based on information from presentations/tasks"),
    ("Listening to Various Types of Information", "Practising pronunciation of words from oral, audio and audio-visual sources"),
    ("Producing Short and Coherent Oral Messages", "Producing short oral messages"),
    ("Producing Short and Coherent Oral Messages", "Using appropriate tone and register"),
    ("Developing Vocabulary from Conversations and Written Texts", "Building vocabulary from conversations"),
    ("Developing Vocabulary from Conversations and Written Texts", "Building vocabulary from written texts"),
    ("Reading Texts for Comprehension", "Reading for main ideas"),
    ("Reading Texts for Comprehension", "Reading for details"),
    ("Reading Texts for Comprehension", "Reading for inference"),
    ("Lugha na Utamaduni", "Matumizi ya lugha ya Kiswahili kama utambulisho wa Mtanzania"),
    ("Lugha na Utamaduni", "Hadhi ya Kiswahili"),
    ("Lugha na Utamaduni", "Matumizi ya lugha ya Kiswahili kama kielelezo cha utamaduni wa Mtanzania"),
    ("Lugha na Utamaduni", "Umuhimu wa kujifunza Kiswahili"),
    ("Sarufi ya Kiswahili", "Matamshi"),
    ("Sarufi ya Kiswahili", "Kusimulia habari kwa kuzingatia lafudhi sahihi"),
    ("Sarufi ya Kiswahili", "Kusimulia habari kwa kuzingatia kiimbo"),
    ("Sarufi ya Kiswahili", "Kusimulia habari kwa kuzingatia mkazo"),
    ("Matumizi ya Kamusi", "Kutumia msamiati kwa usahihi"),
    ("Matumizi ya Kamusi", "Kutumia taarifa za kamusi katika mawasiliano"),
]