"""Static development-seed data: subjects, form levels, topics, subtopics."""

subjects_data = [
    ("Mathematics", "mathematics"),
    ("Chemistry", "chemistry"),
    ("Physics", "physics"),
]

form_levels = ["I", "II", "III", "IV"]

topics_data = [
    ("mathematics", "Concept of Mathematics", "I"),
    ("mathematics", "Numbers", "I"),
    ("mathematics", "Approximations", "I"),
    ("mathematics", "Ratios and Proportions", "I"),
    ("mathematics", "Algebra", "I"),
    ("mathematics", "Coordinate Geometry", "I"),
    ("mathematics", "Geometry", "II"),
    ("mathematics", "Trigonometry", "III"),
    ("chemistry", "Introduction to Chemistry", "I"),
    ("chemistry", "Laboratory Techniques and Safety", "I"),
    ("chemistry", "Fire, Firefighting and Flames", "I"),
    ("chemistry", "Matter", "I"),
    ("chemistry", "Elements, Compounds and Mixtures", "I"),
    ("chemistry", "Chemical Bonding", "II"),
    ("physics", "Introduction to Physics", "I"),
    ("physics", "Measurement", "I"),
    ("physics", "Introduction to Force", "I"),
    ("physics", "Density and Relative Density", "I"),
    ("physics", "Sinking and Floating", "I"),
    ("physics", "Mechanical Properties of Matter", "I"),
    ("physics", "Pressure", "I"),
    ("physics", "Linear Motion", "I"),
    ("physics", "Work, Energy, and Power", "I"),
    ("physics", "Thermodynamics", "II"),
]

subtopics_data = [
    ("Algebra", "Linear Equations"),
    ("Algebra", "Quadratic Equations"),
    ("Geometry", "Triangles"),
    ("Introduction to Chemistry", "Concept of Chemistry"),
    ("Introduction to Chemistry", "Relationships of Chemistry with other related disciplines"),
    ("Introduction to Chemistry", "Applications of Chemistry in the development of a modern society"),
    ("Laboratory Techniques and Safety", "Laboratory Safety Measures"),
    ("Laboratory Techniques and Safety", "Handling Chemicals Safely / Safety Signs"),
    ("Laboratory Techniques and Safety", "Laboratory Rules"),
    ("Laboratory Techniques and Safety", "First Aid and First Aid Kit"),
    ("Laboratory Techniques and Safety", "Basic Chemistry Laboratory Apparatus"),
    ("Fire, Firefighting and Flames", "Fire (Components needed to start fire)"),
    ("Fire, Firefighting and Flames", "Firefighting (Portable fire extinguishers)"),
    ("Fire, Firefighting and Flames", "Flames (Bunsen burner, parts, and characteristics of flames)"),
    ("Matter", "States of Matter"),
    ("Matter", "Changes in States of Matter"),
    ("Matter", "Particulate and Kinetic Nature of Matter"),
    ("Matter", "Physical and Chemical Changes"),
    ("Elements, Compounds and Mixtures", "Elements and Chemical Symbols"),
    ("Elements, Compounds and Mixtures", "Metals and Non-metals"),
    ("Elements, Compounds and Mixtures", "Compounds and Mixtures"),
    ("Elements, Compounds and Mixtures", "Solutions, Suspensions and Emulsions"),
    ("Elements, Compounds and Mixtures", "Separation of Mixtures"),
    ("Introduction to Physics", "Concept of Physics"),
    ("Introduction to Physics", "Contribution of Physics to the development of modern society"),
    ("Introduction to Physics", "Theories and principles of Physics"),
    ("Measurement", "Concept of Measurement"),
    ("Measurement", "Physical Quantity"),
    ("Measurement", "Basic Equipment/Apparatus and their uses"),
    ("Introduction to Force", "Concept of Force"),
    ("Introduction to Force", "Effects of Forces"),
    ("Introduction to Force", "Types of Forces"),
    ("Density and Relative Density", "Concept of Density"),
    ("Density and Relative Density", "Relative Density of a Substance"),
    ("Sinking and Floating", "Concept of Sinking and Floating"),
    ("Sinking and Floating", "Concept of Upthrust"),
    ("Sinking and Floating", "Archimedes' Principle"),
    ("Sinking and Floating", "Law of Floatation"),
    ("Mechanical Properties of Matter", "Concept of Elasticity"),
    ("Mechanical Properties of Matter", "Adhesion and Cohesion"),
    ("Mechanical Properties of Matter", "Surface Tension"),
    ("Mechanical Properties of Matter", "Capillarity"),
    ("Pressure", "Concept of Pressure"),
    ("Pressure", "Pressure due to Solids"),
    ("Pressure", "Pressure in Liquids"),
    ("Pressure", "Atmospheric Pressure"),
    ("Linear Motion", "Concept of Motion"),
    ("Linear Motion", "Distance and Displacement"),
    ("Linear Motion", "Speed and Velocity"),
    ("Linear Motion", "Acceleration"),
    ("Linear Motion", "Equation of Linear Motion"),
    ("Linear Motion", "Motion under Gravity"),
    ("Work, Energy, and Power", "Concept of Work"),
    ("Work, Energy, and Power", "Concept of Energy"),
    ("Work, Energy, and Power", "Concept of Power"),
    ("Concept of Mathematics", "Meaning of Mathematics"),
    ("Concept of Mathematics", "Branches of Mathematics"),
    ("Concept of Mathematics", "Relationship between Mathematics and other Subjects"),
    ("Concept of Mathematics", "Importance of Mathematics"),
    ("Numbers", "Concept of Numbers"),
    ("Numbers", "Rational Numbers"),
    ("Numbers", "Irrational Numbers"),
    ("Numbers", "Real Numbers"),
    ("Numbers", "Inequalities in Real Numbers"),
    ("Numbers", "Absolute Value of a Real Number"),
    ("Approximations", "Meaning of Approximations"),
    ("Approximations", "Rounding off Numbers"),
    ("Approximations", "Significant Figures"),
    ("Approximations", "Approximations in Calculations"),
    ("Ratios and Proportions", "Ratios"),
    ("Ratios and Proportions", "Proportions"),
    ("Coordinate Geometry", "Basic Concepts of Coordinate Geometry"),
    ("Coordinate Geometry", "Gradient of a Straight Line"),
    ("Coordinate Geometry", "Equation of a Straight Line"),
    ("Coordinate Geometry", "General Equation of a Straight Line"),
    ("Coordinate Geometry", "Graphing Linear Equations"),
    ("Coordinate Geometry", "Solving Linear Simultaneous Equations Graphically"),
]